name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi thanks for creating your first issue at Maps, we are looking to address it soon.'
        pr-message: 'Congratulations!! You have made your first PR at Maps, we will soon review it.'
